### PR TITLE
GRPC_HEALTH_PROBE_VERSION=v0.3.5

### PR DESCRIPTION
**Pull request by mathieu-benoit**
few security fixes and improvements since 0.2.0: https://github.com/grpc-ecosystem/grpc-health-probe/releases

### CODE REVIEW

**Review by simonz130 — APPROVED** [review]

**Comment by simonz130** [comment]
@mathieu-benoit - please check why CI is failing so we can merge it.

**Comment by mathieu-benoit** [comment]
Thanks @simonz130, I'm talking to @Daniel-Sanche as we speak to see what's happening, because I'm not able to get information from the CI logs to understand what's happening. Will keep you posted as soon as we have progress here.

**Comment by Daniel-Sanche** [comment]
Ok, I cleared up some disk space, and it looks like the CI logs are working again! The CI system is through an error for conflicting dependency versions though. Are you able to build your branch locally?

**Comment by mathieu-benoit** [comment]
Like discussed, dependency with that one: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/591.

**Comment by mathieu-benoit** [comment]
Looks like we are good here now @simonz130, thanks @Daniel-Sanche for fixing the CI issues!

**Pull request merged**
