### PR TITLE
Change to use go module and dependent OTel packages up to date

### PR DESCRIPTION
**Pull request by ymotongpoo**
- Remove dep dependency from shippingservice, checkoutservice, productcatalogservice
- Update dependent OTel library version to v0.17.0
- Update dependent proto version to v1.35.0

Moved the fix branch from the fork to this repo. Replacing #637

### CODE REVIEW

**Comment by Daniel-Sanche** [comment]
Hmm it seems like this is having issues with the CI. I tried running it locally, and the producatcatalogservice wouldn't start. I'm seeing this error:

```
  Warning  Failed     3m26s (x4 over 4m17s)  kubelet            Error: failed to start container "server": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/productcatalogservice\": permission denied": unknown
```

Is it working for you?

**Comment by ymotongpoo** [comment]
I wasn't sure why it causes "permission denied" error. At least, my local environment successfully build the docker image of productcatalogservice by `docker build` command.

**Comment by Daniel-Sanche** [comment]
Have you been trying to run it in a GKE cluster? It may be an IAM issue, or something that only comes up when run. 

Let me know if you need pointers for how to build the project or anything

**Comment by ymotongpoo** [comment]
Closing this PR because of messy rebase issue. Will submit the replacement.

**Pull request closed without merging**
