### PR TITLE
fix: update variable name to avoid `unbound variable` error when running `sandboxctl`

### LINKED ISSUE #1045: [Bug]: `unbound variable` error when running `sandboxctl`
### Version of Cloud Ops Sandbox

0.9.2

### Your client machine OS?

Linux

### Tell us, what is a problem?

With a fresh `git clone` installation, `sandboxctl` outputs an `unbound variable` error on every call. No big deal but users might wonder if something is wrong.

Example:

```sh
XXXXXXXX@cloudshell:~/cloud-ops-sandbox/provisioning$ ./sandboxctl
./sandboxctl: line 214: VERSION: unbound variable
sandboxctl 
usage: sandboxctl [SUBCOMMAND] [OPTION]...

Create or destroy Cloud Ops Sandbox in a Google Cloud environment. Options
specified over flags 

SUBCOMMANDS:
  create                              Create will attempt to launch a new Cloud
                                      Ops Sandbox
[...]
```

### What you expected to happen?

I expected the current version of `sandboxctl` to be displayed instead of the `unbound variable` error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lvaylet**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [X] Make sure to open an issue before writing your code! That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Your change follows guidelines in the [Contributor guide](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/CONTRIBUTING.md)
- [X] Communicate test infrastructure changes, i.e. API enablement, secrets
- [X] Appropriate docs were updated (if necessary)

🛠️ Fixes #1045

### CODE REVIEW

**Comment by lvaylet** [comment]
fixes #1045

**Comment by lvaylet** [comment]
Hi @minherz, I am not sure how to fix the `header-check` error above. Seems like some files are missing after the issue templates were updated.

**Comment by lvaylet** [comment]
I was unable to pick a license for these GitHub issue templates. I am also pretty sure we do not need one so I decided to add the issue templates to the list of files to ignore when checking for missing license headers. See https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint for more details.

**Comment by minherz** [comment]
@lvaylet thank you for the submission. Does the fix of the `--version` parameter in `sandboxctl` justify releasing a new (patch) version of the Cloud Ops Sandbox? This fix was incorporated into the work toward 0.10 version. Unless you are aware about high demand for this fix, it is preferred to invest time into releasing 0.10 as soon as possible.

The change to the issue templates is already in the main branch (this is the only way to support issue templates). 
I've rebased the `release/0.9` branch to include these changes into the release 0.9 as well if we will decide to release more (patch) versions for 0.9. Please, rebase your branch to the current `release/0.9` to avoid committing the changes of the issue templates as a separate changes and avoid tangled commit history.

**Comment by lvaylet** [comment]
@minherz Targeting 0.10 is fine with me.

**Comment by minherz** [comment]
Closing this PR to postpone the fix to 0.10

**Pull request closed without merging**
